import { makeStyles } from '@material-ui/core/styles';

const styles = () =>
	makeStyles({
		root: {
			position: 'sticky',
			top: '0',
			zIndex: '2',
			background: 'white',
			padding: '0 16px',
		},
		body: {
			display: 'flex',
		},
		background: {
			height: '24px',
			background: 'white',
		},
		filter: {
			height: '48px',
			width: '48px',
			background: '#F2F2F7',
			borderRadius: '100%',
			marginRight: '16px',
			cursor: 'pointer',
			display: 'flex',
			flexDirection: 'column',
			justifyContent: 'center',
			alignItems: 'center',
		},
		filterIcon: {
			height: '22px',
			width: '22px',
			margin: '0 auto',
		},
		icon: {
			marginRight: '24px',
			height: '18px',
			width: '18px',
			marginTop: '5px',
		},
		inputWrapper: {
			padding: '10px 24px',
			width: '100%',
			maxWidth: '100%',
			borderRadius: '36px',
			margin: '0 auto',
			background: '#F2F2F7',
			display: 'flex',
		},
		input: {
			fontSize: '18px',
			fontWeight: 500,
			lineHeight: '28px',
			padding: 0,
			background: 'transparent',
			border: 'none',
			flexGrow: '1',
		},
		clearIcon: {
			height: '28px',
			width: '28px',
			cursor: 'pointer',
			color: '#757575',
		},
		bumper: {
			height: '24px',
			background: 'white',
		},
		mobileRoot: {
			position: 'sticky',
			top: '0',
			zIndex: '2',
			padding: '16px',
			background: '#F9F9F9',
			borderBottom: '1px solid #DBDBDB',
		},
		mobileRootHeader: {
			display: 'flex',
			marginBottom: '16px',
			alignItems: 'baseline',
		},
		mobileTitle: {
			margin: '0',
			fontSize: '34px',
			lineHeight: '40px',
			fontWeight: 'bold',
		},
		mobileVersion: {
			margin: '0',
			fontSize: '12px',
			lineHeight: '14px',
		},
		mobileIcon: {
			marginRight: '12px',
			height: '16px',
			width: '16px',
			marginTop: '3px',
		},
		mobileInputWrapper: {
			padding: '7px 10px',
			width: '100%',
			maxWidth: '100%',
			borderRadius: '10px',
			margin: '0 auto',
			background: '#E8E8E9',
			display: 'flex',
		},
		mobileInput: {
			fontSize: '16px',
			fontWeight: 500,
			lineHeight: '22px',
			padding: 0,
			background: 'transparent',
			border: 'none',
			flexGrow: '1',
		},
		mobileClearIcon: {
			height: '22px',
			width: '22px',
			cursor: 'pointer',
			color: '#757575',
		},
		mobileFilter: {
			height: '30px',
			width: '30px',
			background: '#E4E4E5',
			borderRadius: '100%',
			cursor: 'pointer',
			display: 'flex',
			flexDirection: 'column',
			justifyContent: 'center',
			alignItems: 'center',
		},
		mobileFilterIcon: {
			height: '16px',
			width: '16px',
			margin: '0 auto',
		},
		grow: {
			flexGrow: '1',
		},
	});

export default styles;
